name: 'Trigger GitLab CI'
description: 'Trigger GitLab CI Job using the Pipeline API'
inputs:
  host:
    description: 'GitLab CI Host'
    required: true
  port:
    description: 'GitLab CI Host port'
    default: 443
  ca-bundle:
    description: 'CA bundle to use for connections to GitLab'
    required: true
  project-id:
    description: 'GitLab project ID'
    required: true
  token:
    description: 'GitLab CI Token'
    required: true
  ref:
    description: 'Trigger GitLab CI pipeline of a specific ref (branch or tag)'
    default: master
  delay:
    description: 'Time to wait before re-checking status of GitLab CI job status in ms.'
    default: 30000

runs:
  using: 'node12'
  main: 'dist/index.js'
